version: "3.7"

services:
  web:
    container_name: docker-database-alpine-web
    build:
      context: ./docker/httpd
    #   context: ./docker/nginx
    # volumes:
    #   - ./docker/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf:z
    #   - ./docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:z
    ports:
      - 8080:80
    depends_on:
      - php
      # - db
  php:
    container_name: docker-database-alpine-php
    build:
      context: ./docker/php
    volumes:
      - ./docker/php/conf/php.ini:/usr/local/etc/php/php.ini:z
      - ./docker/php/conf/www.conf:/usr/local/etc/php-fpm.d/www.conf:z
      - ./phpinfo/phpinfo.php:/var/www/html/phpinfo.php:z
  # db:
  #   container_name: docker-database-mariadb-db
  #   image: mariadb/server:latest
  #   volumes:
  #     - ./docker/mysql/conf/my.cnf:/etc/mysql/conf.d/my.cnf:z
  #   environment:
  #     MARIADB_DATABASE: docker-database
  #     MARIADB_USER: docker-database
  #     MARIADB_PASSWORD: hoge
  #     MARIADB_ROOT_PASSWORD: test
  #   ports:
  #     - 13306:3306
